# Generated by Django 4.2.1 on 2023-05-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='warnty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
